### ISSUE TITLE
Permissions for the PulseAudio org

### ISSUE THREAD

**Issue by ford-prefect** [flathub/org.pulseaudio.pavucontrol#2]
Hi @nedrichards, would it be possible to share write access to the repo with the PulseAudio organisation? Or for @tanuk if that's not possible?

**Comment by wjt** [comment]
@barthalion ?

**Comment by barthalion** [comment]
Invited @tanuk. I intend to add organizations support, "tracked" at https://github.com/flathub/flathub/issues/1678.
