### ISSUE TITLE
Environment variable is removed when configuring permissions via Flatseal

### ISSUE THREAD

**Issue by madhogs** [flathub/org.pulseaudio.pavucontrol#21]
Hi,

Not sure if this is an issue with this package, pavucontrol itself or flatseal but the environment variable `PULSE_PROP_media.category=Manager` is not considered valid by most shells and flatseal as it contains a dot.
Configuring any permissions for this application causes this variable to be removed which then results in the application not working.

Thanks

**Comment by ford-prefect** [comment]
Could you use `PULSE_PROP="media.category=Manager"`?

**Comment by madhogs** [comment]
Changing the environment variable to `PULSE_PROP="media.category=Manager"` prevents pavucontrol from being able to control pulseaudio, changing anything in pavucontrol has no effect with this set.

**Comment by E-D-W-I-N** [comment]
Same issue here. Flatseal show this environment variable as non valid
![image](https://github.com/flathub/org.pulseaudio.pavucontrol/assets/22594525/22350fa6-a7e0-4958-8fd0-4f46e1eece2b)

Changing any of permissions causes this variable to be removed (it becomes `PULSE_PROP_media.category=`) and applications can't make any changes anymore

`PULSE_PROP="media.category=Manager"` is not working at all

Workaround:
1. Set app permissions as you want with Flatseal
2. Go to `.local/share/flatpak/overrides` and open file `org.pulseaudio.pavucontrol` with any text editor and change variable to `PULSE_PROP_media.category=Manager`
3. Now pavucontrol is working. Flatseal still shows this variable as non valid but if you wont make any changes to permission this variable won't change

Assuming this dot in variable name is not considered valid by most shells (and also Flatseal) I guess is up to this package to change it. Apps like Flatseal shouldn't make any hacks to workaround this

**Comment by ford-prefect** [comment]
From what I see in the [POSIX shell specification](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08), `PULSE_PROP_media.category` is a valid name for an environment variable. I think this might be one for Flatseal to fix.

**Comment by ford-prefect** [comment]
Seems to be fixed in Flatseal now.
