### ISSUE TITLE
Mark as verified

### ISSUE THREAD

**Issue by wjt** [flathub/org.pulseaudio.pavucontrol#25]
Flathub now has the ability to mark an app as verified.

@ford-prefect do you know whomst has the ability to add a file to the pulseaudio.org website? Here are the instructions from <https://flathub.org/apps/manage/org.pulseaudio.pavucontrol>:

> Create a page at https://pulseaudio.org/.well-known/org.flathub.VerifiedApps.txt containing the following token:
> `e47cdb52-f9f7-4efb-bdc9-9fe9b9a9222c`
> If the page already exists, add the token to it.

That URL currently redirects to https://www.freedesktop.org/wiki/Software/PulseAudio/ and I believe the verification follows `302 Found` so one probably *could* just add that token to https://cgit.freedesktop.org/wiki/www/tree/Software/PulseAudio.mdwn, maybe in a `<!-- comment -->` if those are preserved by IkiWiki. Not really in the spirit of `.well-known` but it might work.

**Comment by ford-prefect** [comment]
imst the one who could do it, and I did -- I looked at this before, but didn't figure out it'll follow the redirect.

ikiwiki needs a plugin for comments, and I found out by experimentation that we don't actually have that on fd.o, but now that it's verified, I'll remove the code (worst case, we can put it back if required).

**Comment by wjt** [comment]
> worst case, we can put it back if required

I confirmed on the Flathub Matrix channel that Flathub does not currently automatically rescan the verification codes, but that's a "not yet" rather than "by design". So at some indeterminate point we can expect to need to put it back (or put a real file at that URL), but for now, we're fine.

**Comment by ford-prefect** [comment]
Gotcha, we can fix it up then. I tried to see if it was tractable to move off ikiwiki so it'd be easier to switch to some static site generator and manage things ourselves, but it was painful enough that I gave up. Maybe we can add a custom redirect for the `.well-known` to some inside page and keep the verification code there (or just suck it up and let it be at the bottom of the wiki)
