### ISSUE TITLE
Move appstream data upstream

### ISSUE THREAD

**Issue by ford-prefect** [flathub/org.pulseaudio.pavucontrol#3]
This should be doable once upstream drops intltool (pending: https://gitlab.freedesktop.org/pulseaudio/pavucontrol/merge_requests/16).

**Comment by wjt** [comment]
Note that we can't just lift the appdata file from this repo because it assumes the app's called `org.pulseaudio.pavucontrol`, not `pavucontrol`. Unless there's appetite for renaming it upstream, the path of least resistance is to change `<id>` and `<launchable>` to `pavucontrol` and `pavucontrol.desktop` respectively, remove `<provides>`, and set `rename-appdata-file` in the Flatpak manifest

**Comment by tanuk** [comment]
>  Note that we can't just lift the appdata file from this repo because it assumes the app's called `org.pulseaudio.pavucontrol`, not `pavucontrol`.

What does "called" mean here exactly? Are there some problems expected from renaming to `org.pulseaudio.pavucontrol`? Is it somehow visible to users?

**Comment by wjt** [comment]
If you rename `pavucontrol.desktop` to `org.pulseaudio.pavucontrol.desktop`, existing shortcuts will disappear from the GNOME Shell sidebar (and presumably the equivalents on other desktops) unless it is added to [this hardcoded list](https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/appFavorites.js). Not the end of the world but worth being aware of.

**Comment by ford-prefect** [comment]
In a timely response, I'm a bit worried that will break non-GNOME launchers. If that is a legitimate concern, I guess we should do what @wjt suggests as the alternative.

**Comment by AsciiWolf** [comment]
> Note that we can't just lift the appdata file from this repo because it assumes the app's called `org.pulseaudio.pavucontrol`, not `pavucontrol`. Unless there's appetite for renaming it upstream, the path of least resistance is to change `<id>` and `<launchable>` to `pavucontrol` and `pavucontrol.desktop` respectively, remove `<provides>`, and set `rename-appdata-file` in the Flatpak manifest

Please, consider moving the AppStream metadata file to upstream. It would help users [on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1904439) and many other distributions.

You can keep both the actual desktop file name and appstream id/file name, just change the current launchable tag to `<launchable type="desktop-id">pavucontrol.desktop</launchable>` in the file. I think that the flatpak-builder should automatically replace it with the correct launchable id.

**Comment by AsciiWolf** [comment]
https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/issues/127

**Comment by wjt** [comment]
https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/merge_requests/82

**Comment by ford-prefect** [comment]
And this is merged now, thank you Will!
