### ISSUE TITLE
Update runtime to 20.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.pulseaudio.pavucontrol#4]

**Comment by wjt** [comment]
bot, build

Edit: oh, this isn't a PR. This isn't a high priority for me personally but if someone wants to send a PR, great.

**Comment by nedrichards** [comment]
Also, why now? This isn't like previous situations where the prior runtime is out of security support.

**Comment by Eonfge** [comment]
Well, time for 20.08

**Comment by wjt** [comment]
PR welcome!

**Comment by Eonfge** [comment]
Made a pull request, #8
