### ISSUE TITLE
doesn't start on Xorg

### ISSUE THREAD

**Issue by swick** [flathub/org.pulseaudio.pavucontrol#7]
Fails with
```
(pavucontrol:2): Gtk-WARNING **: 13:56:56.597: cannot open display: 
```
Same error with `--socket=fallback-x11 --socket=x11`

**Comment by wjt** [comment]
Can you give a little more information about your environment? I primarily use this Flatpak on Endless OS which, regrettably, is X11-only. It works fine for me.

**Comment by swick** [comment]
This is on Fedora 32.20200724.0 (Silverblue) with Gnome Shell 3.36.4 or awesomewm.

**Comment by m132** [comment]
This is a GNOME bug, a defunct Wayland socket is left in XDG runtime directory after logging out of a Wayland session, which confuses Flatpak and consequently breaks GUI apps. Run `rm $XDG_RUNTIME_DIR/wayland-0` or restart and log into X11 session directly.

**Comment by swick** [comment]
thanks. is this tracked anywhere?
